name: Build Fabric Mod from ZIP

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Unzip source code
        run: unzip -o mod.zip -d .

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Remove Gradle cache (fix potential issues)
        run: rm -rf ~/.gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Run Gradle Build
        run: ./gradlew build --stacktrace --info

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: FabricMod
          path: build/libs/*.jar
